### PR TITLE
Andrew rider application entity

### LINKED ISSUE #45: Create entity class for #21

### PR DESCRIPTION
**Pull request by andrewthaii**
Finished writing the entity class with its respected variables. closes #45

### CODE REVIEW

**Review by abcdefucsb — COMMENTED** [review]
Looks neat. Good work!

**Review by abcdefucsb — APPROVED** [review]
Looks neat. Good work! LGTM!

**Review by abcdefucsb — APPROVED** [review]
Reviewed in the previous PR. LGTM!

**Review by pconrad — APPROVED** [review]
LGTM

**Pull request merged**
