### PR TITLE
Andrew rider application repo

### LINKED ISSUE #47: Create Repository File for #21

### PR DESCRIPTION
**Pull request by andrewthaii**
Finished writing the Repository file for the RiderApplication. closes #47

### CODE REVIEW

**Review by abcdefucsb — APPROVED** [review]
Looks good! LGTM!

**Review by abcdefucsb — APPROVED** [review]
Reviewed in the previous PR. LGTM!

**Comment by andrewthaii** [comment]
Merging conflict is fixed

**Review by abcdefucsb — DISMISSED** [review]

**Review by abcdefucsb — APPROVED** [review]
merge conflict from the entity class is fixed and the repo file is done.
LGTM!

**Review by abcdefucsb — DISMISSED** [review]

**Review by abcdefucsb — APPROVED** [review]
merge conflict from the entity class is fixed and the repo file is done.
LGTM!

**Review by abcdefucsb — DISMISSED** [review]
merge conflict from the entity class is fixed and the repo file is done.
LGTM!

**Review by cjyu81 — DISMISSED** [review]
LGTM

**Pull request merged**
